// export const SOM_MUTATION = 'SOM_MUTATION'
// export const SOM_MUTATION1 = 'SOM_MUTATION1'
const mutations = {
  INDEX_MUTATION: 'INDEX_MUTATION',
  INDEX_GETTERS: 'INDEX_GETTERS',
  INDEX_ACTIONS: 'INDEX_ACTIONS',

  PUB_MUTATION: 'PUB_MUTATION',
  PUB_GETTERS: 'PUB_GETTERS',
  PUB_ACTIONS: 'PUB_ACTIONS',

  ABOUT_MUTATION: 'ABOUT_MUTATION',
  ABOUT_ACTIONS: 'ABOUT_ACTIONS',
  ABOUT_GETTERS: 'ABOUT_GETTERS',
}
export default mutations          